### ISSUE TITLE
Ember error on runloop `next()` call

### ISSUE THREAD

**Issue by patrickberkeley** [kaliber5/ember-stargate#144]
We are periodically seeing the following error:

```
index.js:172 Uncaught Error: Assertion Failed: You attempted to access the `concatenatedProperties` property (of <(unknown):ember1140>).
Since Ember 3.1, this is usually fine as you no longer need to use `.get()`
to access computed properties. However, in this case, the object in question
is a special kind of Ember object (a proxy). Therefore, it is still necessary
to use `.get('concatenatedProperties')` in this case.

If you encountered this error because of third-party code that you don't control,
there is more information at https://github.com/emberjs/ember.js/issues/16148, and
you can help us improve this error message by telling us more about what happened in
this situation.
```

From the stacktrace it appears to be cause by:

https://github.com/kaliber5/ember-stargate/blob/f8a033145ec591464e7c5908b17eb0a05f4c0cde/addon/components/portal.js#L11

**Comment by patrickberkeley** [comment]
@simonihmig thanks for following up. We haven't seen this issue in awhile now. I'm assuming what was happening was something we were rendering with stargate was using another addon that did access `concatenatedProperties`, but that it's since been fixed.

Closing.

**Comment by simonihmig** [comment]
Even better, thanks for the quick feedback!
