### ISSUE TITLE
integration test recommendations

### ISSUE THREAD

**Issue by st-h** [kaliber5/ember-stargate#23]
Thanks for creating this addon - I just started to replace my pre-octane usage of ember-elsewhere and it works great so far.

One question, though. Is there any recommendation how to deal with integration tests? If I write a component, which makes use of this addon to render content somewhere else, I would like to assert the content that should be rendered somewhere else. 

Without doing anything, this content currently just never shows up. To work around it one can also add the target to the render instruction. For instance rendering a portal to display modal messages and the component under test:

```
    await render(hbs`
      <PortalTarget @name="modal" />
      <Modal::Info @text={{this.text}} />
    `);
```

However, this seems somewhat inconvenient.

**Comment by simonihmig** [comment]
Hm, but I do think this would be the way to go!
* I cannot think of any good solution that "magically" creates that target (with the right name!)
* The modal will not render correctly in the real world (outside tests) also if the portal target does not exist, so having the target explicitly in the tests seems to describe the reality correctly, even if it's a bit more verbose. I would prefer that verbosity over any kind of "magic" that would come with its own caveats. E.g. I see tests also as a way to formally describe the *intended* behavior of what's being tested. If you would somehow obfuscate that there needs to be a portal target in tests, this would suggest by just looking at the test that I could just drop the modal component somewhere and expect it to work, which would not be the case.

**Comment by st-h** [comment]
@simonihmig thanks a lot for your input. I think what you describe sounds reasonable. I'll stick with it for now, as having to add the target when rendering is not too bad. We could probably add some helper, but I am not sure if it really is worth it, as adding the target manually is just a few chars.
