### ISSUE TITLE
onChange doesn't fire on initial render

### ISSUE THREAD

**Issue by meirish** [kaliber5/ember-stargate#527]
I'm not sure if this is related to #10 or not, but we recently found that a hard refresh of our app on a page that renders at least one portal _does not_ call the `onChange` function that's passed to `PortalTarget`. We worked around this by moving our updating to use the yielded `count` which _does_ have the right value.

Is this a bug or intended behavior?

**Comment by simonihmig** [comment]
Hm, sounds like a bug. Thanks for reporting!

There is a [test](https://github.com/kaliber5/ember-stargate/blob/master/packages/test-app/tests/integration/components/portal-test.ts#L250-L289) for `onChange`, but it is only covering the delayed case, not an initial render that already has an active portal.

If you have the time, a PR with such a (failing) test case would help!
